// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCiliumEnvoyHTTPFilters implements CiliumEnvoyHTTPFilterInterface
type FakeCiliumEnvoyHTTPFilters struct {
	Fake *FakeCiliumV2alpha1
	ns   string
}

var ciliumenvoyhttpfiltersResource = v2alpha1.SchemeGroupVersion.WithResource("ciliumenvoyhttpfilters")

var ciliumenvoyhttpfiltersKind = v2alpha1.SchemeGroupVersion.WithKind("CiliumEnvoyHTTPFilter")

// Get takes name of the ciliumEnvoyHTTPFilter, and returns the corresponding ciliumEnvoyHTTPFilter object, and an error if there is any.
func (c *FakeCiliumEnvoyHTTPFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumEnvoyHTTPFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ciliumenvoyhttpfiltersResource, c.ns, name), &v2alpha1.CiliumEnvoyHTTPFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyHTTPFilter), err
}

// List takes label and field selectors, and returns the list of CiliumEnvoyHTTPFilters that match those selectors.
func (c *FakeCiliumEnvoyHTTPFilters) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumEnvoyHTTPFilterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ciliumenvoyhttpfiltersResource, ciliumenvoyhttpfiltersKind, c.ns, opts), &v2alpha1.CiliumEnvoyHTTPFilterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.CiliumEnvoyHTTPFilterList{ListMeta: obj.(*v2alpha1.CiliumEnvoyHTTPFilterList).ListMeta}
	for _, item := range obj.(*v2alpha1.CiliumEnvoyHTTPFilterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ciliumEnvoyHTTPFilters.
func (c *FakeCiliumEnvoyHTTPFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ciliumenvoyhttpfiltersResource, c.ns, opts))

}

// Create takes the representation of a ciliumEnvoyHTTPFilter and creates it.  Returns the server's representation of the ciliumEnvoyHTTPFilter, and an error, if there is any.
func (c *FakeCiliumEnvoyHTTPFilters) Create(ctx context.Context, ciliumEnvoyHTTPFilter *v2alpha1.CiliumEnvoyHTTPFilter, opts v1.CreateOptions) (result *v2alpha1.CiliumEnvoyHTTPFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ciliumenvoyhttpfiltersResource, c.ns, ciliumEnvoyHTTPFilter), &v2alpha1.CiliumEnvoyHTTPFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyHTTPFilter), err
}

// Update takes the representation of a ciliumEnvoyHTTPFilter and updates it. Returns the server's representation of the ciliumEnvoyHTTPFilter, and an error, if there is any.
func (c *FakeCiliumEnvoyHTTPFilters) Update(ctx context.Context, ciliumEnvoyHTTPFilter *v2alpha1.CiliumEnvoyHTTPFilter, opts v1.UpdateOptions) (result *v2alpha1.CiliumEnvoyHTTPFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ciliumenvoyhttpfiltersResource, c.ns, ciliumEnvoyHTTPFilter), &v2alpha1.CiliumEnvoyHTTPFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyHTTPFilter), err
}

// Delete takes name of the ciliumEnvoyHTTPFilter and deletes it. Returns an error if one occurs.
func (c *FakeCiliumEnvoyHTTPFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ciliumenvoyhttpfiltersResource, c.ns, name, opts), &v2alpha1.CiliumEnvoyHTTPFilter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCiliumEnvoyHTTPFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ciliumenvoyhttpfiltersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.CiliumEnvoyHTTPFilterList{})
	return err
}

// Patch applies the patch and returns the patched ciliumEnvoyHTTPFilter.
func (c *FakeCiliumEnvoyHTTPFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumEnvoyHTTPFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ciliumenvoyhttpfiltersResource, c.ns, name, pt, data, subresources...), &v2alpha1.CiliumEnvoyHTTPFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumEnvoyHTTPFilter), err
}
