// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumEnvoyHTTPFilterLister helps list CiliumEnvoyHTTPFilters.
// All objects returned here must be treated as read-only.
type CiliumEnvoyHTTPFilterLister interface {
	// List lists all CiliumEnvoyHTTPFilters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumEnvoyHTTPFilter, err error)
	// CiliumEnvoyHTTPFilters returns an object that can list and get CiliumEnvoyHTTPFilters.
	CiliumEnvoyHTTPFilters(namespace string) CiliumEnvoyHTTPFilterNamespaceLister
	CiliumEnvoyHTTPFilterListerExpansion
}

// ciliumEnvoyHTTPFilterLister implements the CiliumEnvoyHTTPFilterLister interface.
type ciliumEnvoyHTTPFilterLister struct {
	indexer cache.Indexer
}

// NewCiliumEnvoyHTTPFilterLister returns a new CiliumEnvoyHTTPFilterLister.
func NewCiliumEnvoyHTTPFilterLister(indexer cache.Indexer) CiliumEnvoyHTTPFilterLister {
	return &ciliumEnvoyHTTPFilterLister{indexer: indexer}
}

// List lists all CiliumEnvoyHTTPFilters in the indexer.
func (s *ciliumEnvoyHTTPFilterLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumEnvoyHTTPFilter, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumEnvoyHTTPFilter))
	})
	return ret, err
}

// CiliumEnvoyHTTPFilters returns an object that can list and get CiliumEnvoyHTTPFilters.
func (s *ciliumEnvoyHTTPFilterLister) CiliumEnvoyHTTPFilters(namespace string) CiliumEnvoyHTTPFilterNamespaceLister {
	return ciliumEnvoyHTTPFilterNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CiliumEnvoyHTTPFilterNamespaceLister helps list and get CiliumEnvoyHTTPFilters.
// All objects returned here must be treated as read-only.
type CiliumEnvoyHTTPFilterNamespaceLister interface {
	// List lists all CiliumEnvoyHTTPFilters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumEnvoyHTTPFilter, err error)
	// Get retrieves the CiliumEnvoyHTTPFilter from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumEnvoyHTTPFilter, error)
	CiliumEnvoyHTTPFilterNamespaceListerExpansion
}

// ciliumEnvoyHTTPFilterNamespaceLister implements the CiliumEnvoyHTTPFilterNamespaceLister
// interface.
type ciliumEnvoyHTTPFilterNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CiliumEnvoyHTTPFilters in the indexer for a given namespace.
func (s ciliumEnvoyHTTPFilterNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumEnvoyHTTPFilter, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumEnvoyHTTPFilter))
	})
	return ret, err
}

// Get retrieves the CiliumEnvoyHTTPFilter from the indexer for a given namespace and name.
func (s ciliumEnvoyHTTPFilterNamespaceLister) Get(name string) (*v2alpha1.CiliumEnvoyHTTPFilter, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumenvoyhttpfilter"), name)
	}
	return obj.(*v2alpha1.CiliumEnvoyHTTPFilter), nil
}
